spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

client:
  origin: ${CLIENT_ORIGIN}

url:
  callback:
    rankings: ${URL_CALLBACK_RANKINGS}
    places: ${URL_CALLBACK_PLACES}
    keywords: ${URL_CALLBACK_KEYWORDS}

  crawler:
    ranking: ${URL_CRAWLER_RANKING}
    place: ${URL_CRAWLER_PLACE}
    keyword: ${URL_CRAWLER_KEYWORD}